### ISSUE TITLE
CompactJsonFormatter and RenderedCompactJsonFormatter options

### ISSUE THREAD

**Issue by rsr-maersk** [serilog/serilog-formatting-compact#52] opened 2023-04-14 14:22 UTC
Hi, thanks for an awesome package. Request to make a PR / feature change.

We are logging with Serilog via a common adapter to loki.. With CompactJsonFormatter and RenderedCompactJsonFormatter as the formatter.

We would like veryt much that information level is always added to the message. and we can rename the default @fields to specific values. Yes, we can use the ExpressionTemplate formatted also. But this does not include the convenient logic included in the CompactJsonFormatter and RenderedCompactJsonFormatter.

Can I make a PR to add options to the ctor for CompactJsonFormatter and RenderedCompactJsonFormatter? Then ppl can control some behaviour, but keep the default as is?

**Comment by nblumhardt** [comment] 2023-04-14 22:44
Hi, thanks for dropping us a line!

> But this does not include the convenient logic included in the CompactJsonFormatter and RenderedCompactJsonFormatter.

What's missing from `ExpressionTemplate`? Thanks!

**Comment by generik0** [comment] 2023-04-16 06:06
Hi.

I think your main problem is, that using the expression template means we need to change code in 100+ microservices.

But I guess it isn't much of an arguement when we would need to change to use the nine default ctor I propose also.

Our problem is concrete when using Grafana and the log level not being present.
If info level, grafana doesn't adds info.

![image](https://user-images.githubusercontent.com/2411563/232275057-ddf12317-0009-4d8d-a42a-1f7a3b338198.jpeg)

**Comment by nblumhardt** [comment] 2023-04-17 05:06
Hi! Thanks for the extra info. This really seems like a configuration management problem - deploying new logger configuration to 100 microservices is going to need some supporting infrastructure.

Closing as a duplicate of https://github.com/serilog/serilog-formatting-compact/issues/20, but if you need any help with getting `ExpressionTemplate` (or a copy of `CompactJsonFormatter`) set up to your liking, please let me know. Thanks!

**Closed as completed by nblumhardt** 2023-04-17 05:06 UTC
Labels: duplicate
