### ISSUE TITLE
Why Information levels are ommited? 

### ISSUE THREAD

**Issue by abenedykt** [serilog/serilog-formatting-compact#41] opened 2020-12-16 13:55 UTC
https://github.com/serilog/serilog-formatting-compact/blob/1eca9e524cb8b2abc32b08ef1e3f87fed6762f73/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs#L90

**Comment by sungam3r** [comment] 2020-12-16 16:00
This is done to save a little on message size. Apparently, the expectations were that messages with the `Information` level are the main ones for the application.

**Comment by nblumhardt** [comment] 2020-12-17 09:32
Thanks for the note. This is a duplicate of  #13, #19, and #20, with discussion in those threads.

**Closed as completed by nblumhardt** 2020-12-17 09:32 UTC
Labels: duplicate

**Comment by nblumhardt** [comment] 2021-04-29 06:31
[JSON formatting with `ExpressionTemplate`](https://github.com/serilog/serilog-expressions#formatting-with-expressiontemplate) can do this, now.
