### ISSUE TITLE
Is it possible to have method of changing timezone from UTC timezone to system time zone?

### ISSUE THREAD

**Issue by PRGWITHSTYLE** [serilog/serilog-formatting-compact#34] opened 2020-07-23 19:57 UTC
The timestamp seems to only output json with UTC timezone is it possible to configure this to use the systems timezone?

**Comment by nblumhardt** [comment] 2020-07-24 01:12
Hi! This is a duplicate of #27 - cheers!

**Closed as completed by nblumhardt** 2020-07-24 01:12 UTC
Labels: duplicate
