### ISSUE TITLE
Why level info is not present in output

### ISSUE THREAD

**Issue by disklosr** [serilog/serilog-formatting-compact#21] opened 2018-07-19 13:34 UTC
It is stated in documentation that absence of log level means information.

I want to know the reason behind this decision and if there's a way to workaround it and still output the log level in all cases.

**Comment by tsimbalar** [comment] 2018-07-19 19:28
Hi Mazioudi,

this topic is already discussed in #20 and #19 .

I'll close the issue for now, but feel free to reopen if you need more information.

Duplicate of #20 and #19

**Closed as completed by tsimbalar** 2018-07-19 19:28 UTC
