### ISSUE TITLE
Include Information level to the log

### ISSUE THREAD

**Issue by Pzixel** [serilog/serilog-formatting-compact#36] opened 2020-10-15 12:05 UTC
Although not rendering "l : Information" saves a bit of bandwidth it's much less convinient to work with. Consider this JSON is going to ELK or something. Now you can't search for say "Information OR Debug" filter because you just can't create it via UI. You will also have to explain it to every user and users would have to explain it in their own teams.

I suggest to make it at least configurable.

**Comment by nblumhardt** [comment] 2020-10-16 00:10
Hi @Pzixel - thanks for the note. This is a duplicate of #13, #19, and #20, with some discussion in those linked issues.

If you need to configure the format, copying https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs into your project and modifying it is the quickest way to go.

For a super-flexible configurable JSON formatter than can do what you're after, you might be interested in https://nblumhardt.com/2020/10/programmable-serilog-formatting/. The "TL;DR:" from that article is:

```csharp
    .WriteTo.Console(new ExpressionTemplate(
        "{ {@t, @mt, @l, @x, ..@p} }\n"))
```

HTH,
Nick

**Closed as completed by nblumhardt** 2020-10-16 00:10 UTC
Labels: duplicate
